apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sdns-role
  labels:
    app: k8sdns
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]