apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sdns-config
  namespace: kube-system
data:
  config: |
    {
      "dns": {
        "ttl": 30,
        "record_types": ["A", "CNAME", "MX", "TXT"]
      },
      "kubernetes": {
        "service_watch": true,
        "external_ip": true
      }
    }